version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    target-branch: "main"
    schedule:
      interval: "monthly"
